apiVersion: apps/v1
kind: Deployment

metadata:
  name: deploy
  labels:
    app: online-inference
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 0
  selector:
    matchLabels:
      app: online-inference
  template:
    metadata:
      name: deploy
      labels:
        app: online-inference
    spec:
      containers:
      - image: tibarska/model:v6
        name: deploy
        ports:
          - containerPort: 8000
        resources:
          requests:
            memory: "1Gi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
